### ISSUE TITLE
when i switch java version , exception occur

### ISSUE THREAD

**Issue by qidawei07** [jagodevreede/sdkman-ui#46]
**when i switch java version , exception occur**
![Snipaste_2024-11-26_23-12-32](https://github.com/user-attachments/assets/8c05b8fa-f7bb-4330-871b-f3c9dda05b0b)
java.lang.IllegalStateException: Not on FX application thread; currentThread = Thread-9
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:294)
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:475)
	at javafx.stage.Window.setShowing(Window.java:1238)
	at javafx.stage.Window.hide(Window.java:1264)
	at javafx.stage.Stage.close(Stage.java:1258)
	at io.github.jagodevreede.sdkmanui.controller.MainScreenController.exitApplication(MainScreenController.java:456)
	at io.github.jagodevreede.sdkmanui.view.VersionView.lambda$getGlobalActionEventHandler$2(VersionView.java:155)
	at io.github.jagodevreede.sdkmanui.service.TaskRunner$1.call(TaskRunner.java:25)
	at io.github.jagodevreede.sdkmanui.service.TaskRunner$1.call(TaskRunner.java:22)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1426)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.lang.Thread.run(Thread.java:833)
	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704)
	at com.oracle.svm.core.windows.WindowsPlatformThreads.osThreadStartRoutine(WindowsPlatformThreads.java:143)

**Comment by jagodevreede** [comment]
Does this occur when switching and opting for the "yes and close" option?

**Comment by qidawei07** [comment]
> Does this occur when switching and opting for the "yes and close" option? Please give the latest [early-access](https://github.com/jagodevreede/sdkman-ui/releases/tag/early-access) build a try, I've updated the code so it should not happen anymore.



> Does this occur when switching and opting for the "yes and close" option? Please give the latest [early-access](https://github.com/jagodevreede/sdkman-ui/releases/tag/early-access) build a try, I've updated the code so it should not happen anymore.

The lastest version works well.
 Great job!!!
